spring:
  mongodb:
    uri: ${MONGO_URL}
    database: ecom_user
  rabbitmq:
    addresses: ${RABBITMQ_URL}
    connection-timeout: 30000
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

# KEYCLOAK
keycloak:
  admin:
    username: user
    password: user
    server-url: http://localhost:8443
    realm: ecom-app
    client-id: admin-cli
    client-uid: 74d31cf4-5808-43de-93e0-01a079063245